//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDb_SMAEntities : DbContext
    {
        public AppDb_SMAEntities()
            : base("name=AppDb_SMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMA_Inventory> SMA_Inventory { get; set; }
        public virtual DbSet<SMA_Inventory_Category> SMA_Inventory_Category { get; set; }
        public virtual DbSet<SMA_Inventory_Category_Type> SMA_Inventory_Category_Type { get; set; }
        public virtual DbSet<SMA_Lookup_Address> SMA_Lookup_Address { get; set; }
        public virtual DbSet<SMA_Lookup_Contact> SMA_Lookup_Contact { get; set; }
        public virtual DbSet<SMA_Lookup_Customer> SMA_Lookup_Customer { get; set; }
        public virtual DbSet<SMA_Lookup_Designer> SMA_Lookup_Designer { get; set; }
        public virtual DbSet<SMA_Lookup_SalesRep> SMA_Lookup_SalesRep { get; set; }
        public virtual DbSet<SMA_Lookup_User> SMA_Lookup_User { get; set; }
        public virtual DbSet<SMA_Lookup_User_Role> SMA_Lookup_User_Role { get; set; }
        public virtual DbSet<SMA_Lookup_Vendor> SMA_Lookup_Vendor { get; set; }
        public virtual DbSet<SMA_Sale> SMA_Sale { get; set; }
        public virtual DbSet<SMA_Sale_Detail> SMA_Sale_Detail { get; set; }
        public virtual DbSet<SMA_Sale_Detail_Type> SMA_Sale_Detail_Type { get; set; }
        public virtual DbSet<SMA_Sale_Inventory_Xrf> SMA_Sale_Inventory_Xrf { get; set; }
    }
}
