//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMA_Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMA_Inventory()
        {
            this.SMA_Sale_Inventory_Xrf = new HashSet<SMA_Sale_Inventory_Xrf>();
        }
    
        public int ProductionId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<decimal> BookValue { get; set; }
        public string WebRef { get; set; }
        public Nullable<int> EnterUserId { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SMA_Inventory_Category SMA_Inventory_Category { get; set; }
        public virtual SMA_Inventory_Category_Type SMA_Inventory_Category_Type { get; set; }
        public virtual SMA_Lookup_User SMA_Lookup_User { get; set; }
        public virtual SMA_Lookup_Vendor SMA_Lookup_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Sale_Inventory_Xrf> SMA_Sale_Inventory_Xrf { get; set; }
    }
}
