//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMA_Sale_Detail
    {
        public int SaleDetailId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> DetailType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> EnterUserId { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SMA_Lookup_User SMA_Lookup_User { get; set; }
        public virtual SMA_Sale SMA_Sale { get; set; }
        public virtual SMA_Sale_Detail_Type SMA_Sale_Detail_Type { get; set; }
    }
}
