//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMA_Lookup_SalesRep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMA_Lookup_SalesRep()
        {
            this.SMA_Sale = new HashSet<SMA_Sale>();
            this.SMA_Lookup_Customer = new HashSet<SMA_Lookup_Customer>();
        }
    
        public int SalesRepId { get; set; }
        public string SalesRepNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> EnterUserId { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> InActiveDT { get; set; }
        public Nullable<int> InActiveBy { get; set; }
    
        public virtual SMA_Lookup_Contact SMA_Lookup_Contact { get; set; }
        public virtual SMA_Lookup_User SMA_Lookup_User { get; set; }
        public virtual SMA_Lookup_User_Role SMA_Lookup_User_Role { get; set; }
        public virtual SMA_Lookup_User SMA_Lookup_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Sale> SMA_Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Customer> SMA_Lookup_Customer { get; set; }
    }
}
