//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMA_Lookup_Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMA_Lookup_Contact()
        {
            this.SMA_Lookup_Customer = new HashSet<SMA_Lookup_Customer>();
            this.SMA_Lookup_Designer = new HashSet<SMA_Lookup_Designer>();
            this.SMA_Lookup_SalesRep = new HashSet<SMA_Lookup_SalesRep>();
            this.SMA_Lookup_Vendor = new HashSet<SMA_Lookup_Vendor>();
        }
    
        public int ContactId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PrimaryAddressTypeId { get; set; }
        public Nullable<int> PrimaryAddressId { get; set; }
        public Nullable<int> SecondaryAddressTypeId { get; set; }
        public Nullable<int> SecondaryAddressId { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string EmailAddress { get; set; }
        public string IMAddress { get; set; }
        public string WebSite { get; set; }
        public string NativeLauguage { get; set; }
        public Nullable<int> EnterUserId { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SMA_Lookup_Address SMA_Lookup_Address { get; set; }
        public virtual SMA_Lookup_Address SMA_Lookup_Address1 { get; set; }
        public virtual SMA_Lookup_User SMA_Lookup_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Customer> SMA_Lookup_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Designer> SMA_Lookup_Designer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_SalesRep> SMA_Lookup_SalesRep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Vendor> SMA_Lookup_Vendor { get; set; }
    }
}
