//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMA_Lookup_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMA_Lookup_User()
        {
            this.SMA_Inventory = new HashSet<SMA_Inventory>();
            this.SMA_Lookup_Address = new HashSet<SMA_Lookup_Address>();
            this.SMA_Lookup_Contact = new HashSet<SMA_Lookup_Contact>();
            this.SMA_Lookup_Customer = new HashSet<SMA_Lookup_Customer>();
            this.SMA_Lookup_Designer = new HashSet<SMA_Lookup_Designer>();
            this.SMA_Lookup_SalesRep = new HashSet<SMA_Lookup_SalesRep>();
            this.SMA_Lookup_SalesRep1 = new HashSet<SMA_Lookup_SalesRep>();
            this.SMA_Lookup_Vendor = new HashSet<SMA_Lookup_Vendor>();
            this.SMA_Sale_Detail = new HashSet<SMA_Sale_Detail>();
            this.SMA_Sale_Inventory_Xrf = new HashSet<SMA_Sale_Inventory_Xrf>();
            this.SMA_Sale = new HashSet<SMA_Sale>();
            this.SMA_Lookup_User1 = new HashSet<SMA_Lookup_User>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoginName { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> EnterUserId { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Sel { get; set; }
        public Nullable<System.DateTime> InActiveDT { get; set; }
        public Nullable<int> InActiveBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Inventory> SMA_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Address> SMA_Lookup_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Contact> SMA_Lookup_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Customer> SMA_Lookup_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Designer> SMA_Lookup_Designer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_SalesRep> SMA_Lookup_SalesRep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_SalesRep> SMA_Lookup_SalesRep1 { get; set; }
        public virtual SMA_Lookup_User_Role SMA_Lookup_User_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_Vendor> SMA_Lookup_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Sale_Detail> SMA_Sale_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Sale_Inventory_Xrf> SMA_Sale_Inventory_Xrf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Sale> SMA_Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Lookup_User> SMA_Lookup_User1 { get; set; }
        public virtual SMA_Lookup_User SMA_Lookup_User2 { get; set; }
    }
}
